:imagesdir: images
[#syntax]
== Die Asciidoc-Syntax

Die Möglichkeiten, die *asciidoc* zur Texterstellung bietet, sind schier endlos. Um ein grundlegendes Verständnis der

=== Basale Gesaltungselemente in asciidoc

Schauen wir uns als Erstes ein paar einfache Formatierungsmöglichkeiten in *asciidoc* an.

[discrete]
==== Einfache Text-Formatierungen
[source, asciidoc]
----
*fett* <.>
_kursiv_ <.>
`mono` <.>
#markiert# <.>
[.underline]#unterstrichen# <.>
[.line-through]#durchgestrichen# <.>
^hochgestellter^ Text <.>
~tiefgestellter~ Text <.>
----

<.> *fett* +
<.> _kursiv_ +
<.> `mono` +
<.> #markiert# +
<.> [.underline]#unterstrichen# +
<.> [.line-through]#durchgestrichen# +
<.> ^hochgestellter^ Text
<.> ~tiefgestellter~ Text

[discrete]
==== Strukturierende Überschriften

Überschriften sind ein essentieller Bestandteil unserer Texte.

[source, asciidoc]
----
= Der Titel des Dokuments <.>
== Eine Überschrift erster Ordnung <.>
=== Eine Überschrift zweiter Ordnung <.>
==== Eine Überschrift dritter Ordnung
===== Eine Überschrift vierter Ordnung
====== Eine Überschrift fünfter Ordnung
== Eine weitere Überschrift erster Ordnung
----
<.> *Wichtig:* Da ein Dokument nur _einen_ Titel haben kann, darf diese Art der Überschrift nur einmal im gesamten Dokument verwendet werden. Ansonsten kann das *asciidoc*-Dokument nicht in die Zielformate gerendert werden. Das fällt insbesondere dann ins Gewicht, wenn man seine Dokumentation aus verschiedenenen Dateien zusammenstellt. Die Verwendung eines Dokumententitels ist aber optional.
<.> Das html-Äquivalent dieser Überschrift ist `<h1></h1>`.
<.> Das html-Äquivalent dieser Überschrift ist `<h2></h2>`, usw.

[discrete]
==== Infoboxen (Admonition Blocks)
Infoboxen eignen sich, um die Aufmerksamkeit des Lesers auf besonders wichtige oder interessante Informationen zu lenken. *Asciidoc* unterstützt von Haus aus verschiedene Arten von Infoboxen, die sehr leicht zu erzeugen sind.
Folgende Arten von Infoboxen sind möglich: `[NOTE]`, `[TIP]`, `[IMPORTANT]`, `[WARNING]` & `[CAUTION]`.

[source, asciidoc]
----
[WARNING]
Ein Text, auf den der Leser mittels eines Hinweis-Icons hingewiesen werden soll.
----

[WARNING]
Ein Text, auf den der Leser mittels eines Warnhinweis hingewiesen werden soll.

[discrete]
==== URLs und Links
Links erzeugen wir, in dem wir sie einfach als solche in unseren Text einfügen:

[source, asciidoc]
----
https://hiq.de
----
Beispiel: https://hiq.de

Wenn wir einen bestimmten Text mit einem Link hinterlegen wollen, geht das so:

[source, asciidoc]
----
https://hiq.de[HiQ Projects GmbH]
----
Beispiel: https://hiq.de[HiQ Projects GmbH]

=== Cheat Sheets
Deshalb sollte man immer ein Cheat Sheet griffbereit haben, auf dem die wichtigsten Syntax-Eigenschaften von *asciidoc* verankert sind.

[NOTE]
.Cheat Sheets
====
https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/ +
https://www.writethedocs.org/guide/writing/asciidoc/ +
https://powerman.name/doc/asciidoc
====

Für die Zwecke dieses Tutorials reichen die angegeben Cheat Sheets vollkommen aus. Wer aber wirklich tief in *asciidoc* einsteigen möchte, findet eine umfängliche Dokumentation hier:

NOTE: https://docs.asciidoctor.org/asciidoc/latest/

<<<
